blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/AmaliTech-Training-Academy/communityBoard_Team4/discussions
    about: Ask questions or start discussions about the project
  - name: Security Issue
    url: mailto:security@amalitech.com
    about: Report security vulnerabilities privately
