-- =============================================================================
-- DEPRECATED — This file is intentionally disabled.
-- =============================================================================
-- Schema and seed data are now managed exclusively by Flyway:
--
--   db/migration/V1__create_users_posts_comments.sql  — DDL (tables, indexes, FKs)
--   db/migration/V2__seed_data.sql                    — seed users and posts
--
-- spring.sql.init.mode is set to 'never' in application.yml, so Spring will NOT
-- execute this file. It is kept for historical reference only.
-- =============================================================================

