##############################################################################
# modules/secrets/variables.tf
##############################################################################

variable "project_name" {
  description = "Short project name — forms the first segment of every path"
  type        = string
}

variable "environment" {
  description = "Deployment environment (prod | staging | dev)"
  type        = string
}

# ── Database ─────────────────────────────────────────────────────────────────

variable "db_host" {
  description = "RDS PostgreSQL hostname (from rds module output)"
  type        = string
}

variable "db_port" {
  description = "RDS PostgreSQL port"
  type        = number
  default     = 5432
}

variable "db_name" {
  description = "Application database name"
  type        = string
}

variable "db_username" {
  description = "RDS master username"
  type        = string
  sensitive   = true
}

variable "db_password" {
  description = "RDS master password (generated by random_password in root)"
  type        = string
  sensitive   = true
}

# ── Application secrets ───────────────────────────────────────────────────────

variable "jwt_secret" {
  description = "JWT signing key (generated by random_password in root)"
  type        = string
  sensitive   = true
}

# ── Infrastructure endpoints ─────────────────────────────────────────────────

variable "alb_dns_name" {
  description = "ALB public DNS name"
  type        = string
}

variable "ecr_repository_url" {
  description = "ECR repository URL"
  type        = string
}

# ── Monitoring ───────────────────────────────────────────────────────────────

variable "grafana_admin_password" {
  description = "Grafana admin password (generated by random_password in root)"
  type        = string
  sensitive   = true
}

variable "tags" {
  description = "Common resource tags"
  type        = map(string)
  default     = {}
}
